version: '3'

services:
  postgres:
    container_name: ingress-db
    build:
      context: ./postgres
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  ingress-backend:
    container_name: ingress-backend
    build:
      context: ./ingress-backend
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: always

  ingress-frontend:
    container_name: ingress-frontend
    build:
      context: ./ingress-frontend
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "80:80"
    depends_on:
      - ingress-backend

volumes:
  pgdata:
